---
title: "Gestion des schémas de la base Postgre"
output: html_document
date: "2024-06-18"
params:
  num_departement: "38"
  temps_apres: 24
  temps_avant: 23
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

```{r package message=FALSE, warning=FALSE}
library(dplyr)
library(sf)
library(DBI)
source(file = "connexion_db.R")
conn <- connecter()
```

```{r}
nom_com <- "Marseille 3eme"
dbExecute(conn, paste0(
  "SET search_path TO traitement_", params$temps_apres, "_", params$temps_avant, "_cadastre_" , params$num_departement,
  ", cadastre_", params$num_departement, ", public"))
```


```{r voir les schémas contenant les tables nécessaires}
dbGetQuery(conn, paste0(" 
  SELECT DISTINCT
      schemaname,
      tablename
  FROM 
      pg_indexes 
  WHERE 
      tablename LIKE 'parc_%'
  ORDER BY 
      schemaname, tablename;
           "))
```

```{r voir les schémas de traitement}
dbGetQuery(conn, paste0(" 
  SELECT 
      schema_name
  FROM 
      information_schema.schemata
  WHERE 
      schema_name LIKE 'traitement_%';
           "))
```

```{r voir les tables de traitement fixe}
dbGetQuery(conn, paste0(" 
  SELECT 
      schemaname,
      tablename
  FROM 
      pg_tables
  WHERE 
      schemaname = '", paste0("traitement_", params$temps_apres, "_", params$temps_avant, "_cadastre_" , params$num_departement), "'
  ORDER BY 
      schemaname, tablename;
           "))
```

```{r supprimer un schéma de traitement}
dbExecute(conn, paste0(
  "DROP SCHEMA IF EXISTS traitement_", params$temps_apres, "_", params$temps_avant, "_cadastre_", params$num_departement, " CASCADE;"))
```

```{r supprimer tous les schémas de traitement}
schemas_to_drop <- dbGetQuery(conn, "
  SELECT schema_name
  FROM information_schema.schemata
  WHERE schema_name LIKE 'traitement_%';
")

# Générer les commandes DROP SCHEMA
drop_commands <- paste0("DROP SCHEMA IF EXISTS \"", schemas_to_drop$schema_name, "\" CASCADE;")

# Exécuter les commandes DROP SCHEMA
lapply(drop_commands, function(cmd) {
  dbExecute(conn, cmd)
})
```

```{r se sortir des requetes bloquées}
transactions <- dbGetQuery(conn, "
  SELECT
    pid,
    state,
    query,
    age(clock_timestamp(), query_start) AS age,
    usename,
    datname
  FROM pg_stat_activity
  WHERE state != 'idle'
  ORDER BY query_start;
")

for (pid in transactions$pid) {
  dbExecute(conn, paste("SELECT pg_terminate_backend(", pid, ");"))
}
```