---
title: "Prise_en_main"
output: html_document
date: "2024-06-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

## Prise en maain des données

```{r package message=FALSE, warning=FALSE}
library(sf)
library(dplyr)
library(lubridate)
library(mapview)
library(DBI)
library(ggplot2)
library(purrr)
library(webshot)
library(pracma)
library(RColorBrewer)
# webshot::install_phantomjs()
source(file = "connexion_db.R")
conn<-connecter()
DBI::dbListTables(conn)
```

```{r prise en main translation}
is_translation <- function(polygon1, polygon2) {
  coords1 <- st_coordinates(polygon1)[, 1:2]
  coords2 <- st_coordinates(polygon2)[, 1:2]
  
  if (nrow(coords1) != nrow(coords2)) {
    return(FALSE)
  }
  
  translation <- coords1 - coords2
  all(translation == translation[1, ])
}

# Deux polygones visiblement en translation
P <- apres_geom[531,]$geometry
Q <- avant_geom[504,]$geometry

# 531 (P) 504 (Q)

st_area(st_geometry(P))
st_area(st_geometry(Q))
# Surfaces différentes

ggplot() +
  geom_sf(data = st_as_sf(P), fill = "blue", color = "blue") +
  geom_sf(data = st_as_sf(Q), fill = "red", color = "red") +
  theme_minimal() +
  labs(title = "Comparaison des polygones P et Q",
       subtitle = "Polygone P en bleu et polygone Q en rouge")

is_translation(P, Q)
hausdorff_dist(st_coordinates(P)[, 1:2], 
               st_coordinates(Q)[, 1:2])


# Choisir un point de référence dans P et Q 
point_ref_P <- st_coordinates(P)[1, 1:2]
point_ref_Q <- st_coordinates(Q)[1, 1:2]
# Probleme du choix : ils ne sont pas forcement dans le bon ordre...

translation <- point_ref_Q - point_ref_P

P_adjusted <- st_geometry(P) + translation

hausdorff_dist(st_coordinates(P_adjusted)[, 1:2], 
               st_coordinates(Q)[, 1:2])
# Non invariant par rapport à la translation

ggplot() +
  geom_sf(data = st_as_sf(st_set_crs(P_adjusted, 2154)), fill = "blue", color = "blue") +
  geom_sf(data = st_as_sf(Q), fill = "red", color = "red") +
  theme_minimal() +
  labs(title = "Comparaison des polygones P ajusté et Q",
       subtitle = "Polygone P ajusté en bleu et polygone Q en rouge")

centroid_P <- st_centroid(P)
centroid_Q <- st_centroid(Q)

translation <- st_coordinates(centroid_Q)[1, 1:2] - st_coordinates(centroid_P)[1, 1:2]

P_adjusted <- st_geometry(P) + translation

hausdorff_dist(st_coordinates(P_adjusted)[, 1:2], 
               st_coordinates(Q)[, 1:2])

map <- mapview(st_set_crs(P, 2154), col.regions = "green", layer.name = "Polygone P") +
  mapview(st_set_crs(P_adjusted, 2154), col.regions = "lightgreen", layer.name = "Polygone P ajusté centroide") +
  mapview(st_set_crs(Q, 2154), col.regions = "red", layer.name = "Q") +
  mapview(st_set_crs(centroid_P, 2154), col.regions = "blue", layer.name = "Centroid P") +
  mapview(st_set_crs(centroid_Q, 2154), col.regions = "black", layer.name = "Centroid Q")

mapshot(map, url = "cas_translation.html")
```

```{r prise en main rotation}
# Deux polygones visiblement en rotation
P <- apres_geom %>%
  filter(idu == "852000000C0758") %>%
  pull(geometry)

Q <- avant_geom %>%
  filter(idu == "852000000C0758") %>%
  pull(geometry)

st_area(st_geometry(P))
st_area(st_geometry(Q))
# Surfaces différentes

ggplot() +
  geom_sf(data = st_as_sf(P), fill = "blue", color = "blue") +
  geom_sf(data = st_as_sf(Q), fill = "red", color = "red") +
  theme_minimal() +
  labs(title = "Comparaison des polygones P et Q",
       subtitle = "Polygone P en bleu et polygone Q en rouge")

hausdorff_dist(st_coordinates(P)[, 1:2], 
               st_coordinates(Q)[, 1:2])

centroid_P <- st_centroid(P)
centroid_Q <- st_centroid(Q)

translation <- st_coordinates(st_centroid(Q))[1, 1:2] - st_coordinates(st_centroid(P))[1, 1:2]

P_adjusted <- st_geometry(P) + translation

hausdorff_dist(st_coordinates(P_adjusted)[, 1:2], 
               st_coordinates(Q)[, 1:2])

rotation = function(a){
  r = a * pi / 180 #degrées en radians
  matrix(c(cos(r), sin(r), -sin(r), cos(r)), nrow = 2, ncol = 2)
} 

optimize_rotation <- function(geometry1, geometry2) {
  angles <- seq(0, 360, by = 1)
  iou_values <- sapply(angles, function(angle) {
    rotated_geom <-  st_set_crs((geometry1 - st_centroid(geometry1)) * rotation(angle) + st_centroid(geometry1), 2154)
    calculate_iou(rotated_geom, geometry2)
  })
  best_angle <- angles[which.max(iou_values)]
  best_iou <- max(iou_values)
  return(best_angle)
}
P_rotated <-  st_set_crs((P_adjusted - st_centroid(P_adjusted)) * rotation(optimize_rotation(P_adjusted,Q)) + st_centroid(P_adjusted), 2154)

map <- mapview(st_set_crs(P, 2154), col.regions = "green", layer.name = "Polygone P") +
  mapview(st_set_crs(P_adjusted, 2154), col.regions = "#7FFFD4", layer.name = "Polygone P translaté") +
  mapview(st_set_crs(P_rotated, 2154), col.regions = "lightgreen", layer.name = "Polygone P translaté en rotation") +
  mapview(st_set_crs(Q, 2154), col.regions = "red", layer.name = "Q") +
  mapview(st_set_crs(centroid_P, 2154), col.regions = "blue", layer.name = "Centroid P") +
  mapview(st_set_crs(centroid_Q, 2154), col.regions = "black", layer.name = "Centroid Q")

mapshot(map, url = "cas_rotation.html")

map
```

```{r prise en main simplification des polygones}
tolerance = 0.1

P_simplified <- st_simplify(P, dTolerance = tolerance)
Q_simplified <- st_simplify(Q, dTolerance = tolerance)

st_area(st_geometry(P_simplified))
st_area(st_geometry(Q_simplified))

is_translation(P_simplified, Q_simplified)
hausdorff_dist(st_coordinates(P_simplified)[, 1:2], 
               st_coordinates(Q_simplified)[, 1:2])


# Choisir un point de référence dans P et Q 
point_ref_P <- st_coordinates(P_simplified)[1, 1:2]
point_ref_Q <- st_coordinates(Q_simplified)[1, 1:2]
# Probleme du choix : ils ne sont pas forcement dans le bon ordre...

translation <- point_ref_Q - point_ref_P

P_adjusted <- st_geometry(P_simplified) + translation

hausdorff_dist(st_coordinates(P_adjusted)[, 1:2], 
               st_coordinates(Q_simplified)[, 1:2])
# Non invariant par rapport à la translation

centroid_P <- st_centroid(P_simplified)
centroid_Q <- st_centroid(Q_simplified)

translation <- st_coordinates(centroid_Q)[1, 1:2] - st_coordinates(centroid_P)[1, 1:2]

P_adjusted <- st_geometry(P_simplified) + translation

hausdorff_dist(st_coordinates(P_adjusted)[, 1:2], 
               st_coordinates(Q_simplified)[, 1:2])

```


```{r mapview cas simpl nécessaire}
P <- joint_geom[6,]$geometry_avant
Q <- joint_geom[6,]$geometry_apres

translation <- st_coordinates(Q)[1, 1:2] - st_coordinates(P)[1, 1:2]
P_adjusted <- st_geometry(P) + translation
P_simplified <- st_simplify(P, dTolerance = tolerance)
Q_simplified <- st_simplify(Q, dTolerance = tolerance)

calculate_hausdorff_distance(
        P, 
        Q)

calculate_hausdorff_distance(
        P_adjusted, 
        Q)

calculate_hausdorff_distance(
        P_simplified, 
        Q_simplified)

# Exactement le même visuellement


```

```{r découpage}
P <- supp_parc %>%
  filter(idu == "852670000D0264") %>%
  pull(geometry)

Q_1 <- ajout_parc %>% 
  filter(idu == "852670000D0731") %>%
  pull(geometry)

Q_2 <- ajout_parc %>% 
  filter(idu == "852670000D0732") %>%
  pull(geometry)

Q <- st_union(Q_1,Q_2)
# P inclut dans Q (la parcelle supprimée est plus petite que les deux crées)
st_contains(Q, P)
st_covered_by(P,Q)
st_within(P, Q)
st_intersects(P,Q)
st_intersects(Q,P)

st_overlaps(P, Q_1)
st_overlaps(P, Q_2)
st_overlaps(Q_2, P)
st_overlaps(Q_1, P)
st_intersects(Q_1, P)
st_intersects(Q_2, P)
st_intersects(P,Q_1)
st_intersects(P,Q_2)

# st_intersects : Renvoie TRUE si les géométries se touchent au moins en un point. Cela inclut les cas où les géométries se chevauchent partiellement ou totalement, ou simplement se touchent aux bords.
# st_overlaps : Renvoie TRUE si les géométries se chevauchent partiellement, c'est-à-dire qu'elles partagent une partie de leur espace mais aucune d'elles n'est entièrement contenue dans l'autre.

ajout_parc %>%
  st_filter(M, .predicate = st_intersects) %>% 
  st_union %>% 
  calculate_iou(M)

polygons <- list(P = P, M = M)
# Fonction pour calculer l'IOU pour un polygone donné
calculate_iou_for_polygon <- function(polygon, ajout_parc) {
  intersecting_geoms <- ajout_parc %>%
    st_filter(polygon, .predicate = st_intersects)
  
  if (st_is_empty(intersecting_geoms)) {
    return(NA)
  }
  
  # Récupérer les noms des polygones participants
  names_participants <- intersecting_geoms$idu

  # Faire l'union des géométries
  combined_geom <- st_union(intersecting_geoms)
  
  # Calculer l'IOU
  iou_value <- calculate_iou(combined_geom, polygon)
  
  list(iou = iou_value, participants = names_participants)
}

# Appliquer la fonction à chaque polygone
results <- map(polygons, ~ calculate_iou_for_polygon(.x, ajout_parc))
```


```{r connexité}
library(sf)

# Création des données initiales
multipolygon_data <- st_as_sf(data.frame(
  id = 1:5,
  geometry = st_sfc(
    st_multipolygon(list(
      list(rbind(c(0, 0), c(1, 0), c(1, 1), c(0, 1), c(0, 0)))
    )),
    st_multipolygon(list(
      list(rbind(c(1, 0), c(2, 0), c(2, 1), c(1, 1), c(1, 0)))
    )),
    st_multipolygon(list(
      list(rbind(c(0.5, 0.5), c(1.5, 0.5), c(1.5, 1.5), c(0.5, 1.5), c(0.5, 0.5)))
    )),
    st_multipolygon(list(
      list(rbind(c(3, 3), c(4, 3), c(4, 4), c(3, 4), c(3, 3)))  # Polygone distant
    )),
    st_multipolygon(list(
      list(rbind(c(0, 1), c(1, 1), c(1, 2), c(0, 2), c(0, 1)))
    ))
  )
), crs = 4326)
plot(st_geometry(multipolygon_data), col = c("red", "blue", "green", "orange", "purple"), border = "black")

# Définir le polygone donné en entrée
polygone_donne <- st_multipolygon(list(
  list(rbind(c(0, 1), c(1, 1), c(1, 2), c(0, 2), c(0, 1)))
))

# Étape 1: Union de tous les polygones
union_tous <- st_union(multipolygon_data)
largest_polygons <- st_cast(union_tous, "POLYGON")
largest_polygons_sf <- st_sf(geometry = largest_polygons)

# Trouver les polygones individuels qui intersectent le polygone donné
intersections <- st_intersects(largest_polygons_sf, polygone_donne, sparse = FALSE)
parcelles_intersectant_avant <- multipolygon_data %>% 
  st_filter(largest_polygons_sf[intersections,], .predicate = st_intersects)

nom_participants_avant <- parcelles_intersectant_avant$id
```

```{r}
library(sf)

# Créer l'ensemble de multipolygones
multipolygon_data <- st_as_sf(data.frame(
  id = 1:5,
  geometry = st_sfc(
    st_multipolygon(list(
      list(rbind(c(0, 0), c(1, 0), c(1, 1), c(0, 1), c(0, 0)))
    )),
    st_multipolygon(list(
      list(rbind(c(1, 0), c(2, 0), c(2, 1), c(1, 1), c(1, 0)))
    )),
    st_multipolygon(list(
      list(rbind(c(0.5, 0.5), c(1.5, 0.5), c(1.5, 1.5), c(0.5, 1.5), c(0.5, 0.5)))
    )),
    st_multipolygon(list(
      list(rbind(c(3, 3), c(4, 3), c(4, 4), c(3, 4), c(3, 3)))  # Polygone distant
    )),
    st_multipolygon(list(
      list(rbind(c(0, 1), c(1, 1), c(1, 2), c(0, 2), c(0, 1)))
    ))
  )
), crs = 4326)

# Calculer l'enveloppe convexe de l'ensemble des géométries
enveloppe_convexe <- st_convex_hull(st_union(multipolygon_data))

# Afficher le résultat
plot(st_geometry(multipolygon_data), col = 'blue', border = 'black')
plot(st_geometry(enveloppe_convexe), col = 'red', border = 'black')

```


```{r focus parcelle changement de communes}

parc_com_abs_apres <- ajout_parc %>% 
  filter(com_abs != "000")

parc_com_abs_apres <- parc_com_abs_apres %>%
  mutate(idu_avant = paste0(substr(idu,1,2),
                            com_abs, 
                            "000", 
                            substr(idu,9,14))
  )

parc_com_abs_avant <- supp_parc %>% 
  filter(idu %in% parc_com_abs_apres$idu_avant)

df_abs <- parc_com_abs_apres %>%
  st_filter(parc_com_abs_avant, .predicate = st_equals)
# Parcelles n'ayant pas été modifiées mise à part le nom de commune

parc_com_abs_apres <- parc_com_abs_apres %>% 
  filter(!idu %in% df_abs$idu)

parc_com_abs_avant <- parc_com_abs_avant %>% 
  filter(!idu %in% df_abs$idu_avant)

# Attention cas de parcelles crées (n'existant pas avant) mais ayant le numéro de 
# com_abs
```

```{r focus parcelle changement de communes}
map <- mapview(commune, layer.name = "Communes", col.regions = "white", alpha.regions = 0.5) +
  mapview(bordure, layer.name = "Bordures étendues", col.regions = "lightblue", alpha.regions = 0.5) +
  mapview(parc_com_abs_apres, layer.name = "Parcelles abs (état 2024)", col.regions = "purple", alpha.regions = 0.5) +
  mapview(parc_com_abs_avant, layer.name = "Parcelles abs (état 2023)", col.regions = "lightgreen", alpha.regions = 0.5) +
  mapview(ajout_parc, layer.name = "Parcelles ajoutées", col.regions = "purple", alpha.regions = 0.5) +
  mapview(supp_parc, layer.name = "Parcelles supprimées", col.regions = "lightgreen", alpha.regions = 0.5)

mapshot(map, url = "parcelles_abs.html")
```